version: '3'

services:

  icons:
    environment:
      - USER=changeusername
      - USER_PASSWORD=
      - SUDO=true
      - SUDO_REQUIRE_PASSWORD=false
      - ALLOW_SSH_PASSWORD=false
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=pjaa
    volumes:
      - ./ssh/:/home/pjaa/.ssh
    ports:
      - "2222:22"
    stdin_open: true
    tty: true
    container_name: 'icons'